# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprWeb < Formula
  desc "Local web UI for managing stacked pull requests created with spr"
  homepage "https://github.com/gipcompany/spr-web"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.1.0/spr-web_0.1.0_darwin_amd64.tar.gz"
      sha256 "10410928b8693e844718ad3391773a5de4f95acc6d669d900c504da834f971fb"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.1.0/spr-web_0.1.0_darwin_arm64.tar.gz"
      sha256 "af4185e2b83f8c735bdd45854c6646ccc857ea69dff12ef46efb323895d90eef"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.1.0/spr-web_0.1.0_linux_amd64.tar.gz"
      sha256 "f3df21c351ef558dac49feb3b3f00232867b398ceb1a1ffc75e7b616cf569698"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.1.0/spr-web_0.1.0_linux_arm64.tar.gz"
      sha256 "7ce0e4c69cf7a28a6a8eeef186eaaa692df3254df4464d208708928ba62a536c"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  test do
    system "#{bin}/spr-web", "--version"
  end
end
