# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprWeb < Formula
  desc "Local web UI for managing stacked pull requests created with spr"
  homepage "https://github.com/gipcompany/spr-web"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.3.0/spr-web_0.3.0_darwin_amd64.tar.gz"
      sha256 "654b13f95ca04f819b41bac47d7e1aaf8d335b503d3d4e91b5fe59d23776b6b9"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.3.0/spr-web_0.3.0_darwin_arm64.tar.gz"
      sha256 "90406e1f60235a7ca7e48fa4cf8b132118e7fe99c7b8bce6cb33d507029c2010"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.3.0/spr-web_0.3.0_linux_amd64.tar.gz"
      sha256 "1639355852003d8437130d5fd29231134ca892ffbb5b60d0791c0852ccde3a08"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.3.0/spr-web_0.3.0_linux_arm64.tar.gz"
      sha256 "ce365a766a5c6e07f42a38d27d7ae9db596ba6f529ed311ea6b805e691371275"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  test do
    system "#{bin}/spr-web", "--version"
  end
end
