# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprWeb < Formula
  desc "Local web UI for managing stacked pull requests created with spr"
  homepage "https://github.com/gipcompany/spr-web"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.2.0/spr-web_0.2.0_darwin_amd64.tar.gz"
      sha256 "22a9c76e70713ad0b9b0efc38f2be59ee235ca34dab1fdb5a2547b64a43264a9"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.2.0/spr-web_0.2.0_darwin_arm64.tar.gz"
      sha256 "1b5a7cf1cf489cccd10ed52b201e1af49ba0949db931a78945dcd3cf05808b3a"

      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.2.0/spr-web_0.2.0_linux_amd64.tar.gz"
      sha256 "7f245b6e801b2b92a93ac1335273e0fd027fccb474e8a5c83d25b81567c93a6d"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gipcompany/spr-web/releases/download/v0.2.0/spr-web_0.2.0_linux_arm64.tar.gz"
      sha256 "1101a673238eee90170adf43921a78baceff39d82e34d2e9649bddd706a369bf"
      define_method(:install) do
        bin.install "spr-web"
      end
    end
  end

  test do
    system "#{bin}/spr-web", "--version"
  end
end
